import type { State } from "@/lib/types/state";
import { defaultState } from "@/lib/utils/state";
import { midenFaucetAccount } from "@/lib/utils/account";
import defaultScripts from "@/lib/types/default-scripts";
import defaultComponents from "@/lib/types/default-components";
import counterMapContractScript from "@/lib/types/default-scripts/counter-map-contract";
import countReaderScript from "@/lib/types/default-scripts/count-reader";
import {
  defaultAccount,
  getIdentifierPart,
  getRoutingParametersPart,
} from "@/lib/utils/account";
import { defaultProcedureExport } from "@/lib/utils/script";
import { defaultComponent, storageSlotName } from "@/lib/utils/component";

const COUNTER_CONTRACT_ID = "0x37ca9027996b581179acbb1235cc31";
const COUNTER_CONTRACT_ADDRESS =
  "mtst1aqmu4yp8n944syte4ja3ydwvxya399ar_qr7qqq9wr6w";

const state: State = {
  ...defaultState(),
  accounts: [
    midenFaucetAccount("mtst"),
    {
      ...defaultAccount(),
      id: COUNTER_CONTRACT_ID,
      name: "Counter Contract",
      address: COUNTER_CONTRACT_ADDRESS,
      identifier: getIdentifierPart(COUNTER_CONTRACT_ADDRESS),
      routingParameters: getRoutingParametersPart(COUNTER_CONTRACT_ADDRESS),
      isFaucet: false,
      isPublic: true,
      isPrivate: false,
      isRegularAccount: true,
      isNew: false,
      components: ["auth-no-auth", "basic-wallet", "counter-account"],
    },
  ],
  scripts: [
    ...defaultScripts,
    {
      ...counterMapContractScript,
      id: "counter-account",
      name: "counter-account",
      digest:
        "0x3874bfcdc769a48ae5e4e66f0ae9e50438743cdb35bdf258d1d1c3cf71575b26",
      masm: "",
      masp: "TUFTUAAGAAAfY291bnRlci1hY2NvdW50CzAuMS4wAANNQVNUAAAABIoCCRUEAAAAjQAAAEsAAACEAAAAmAAAAI8AAACeAAAATwAAAKIAAAClAAAAGmkDAAEAAAABAAAAAJNbBAAAAAAAAABb/v///wAAAAAHIlv+////AAAAAC0pW/3////+////AFv+////AAAAAAciLSlb/v////7///8AW/7///8AAAAAByItKTAwCFsAAAAAAQAAACMiMVv//////v///1v+////AAAAAAciLSkAW/7////+////AFv+////AAAAAAciB1sEAAAAAAAAAFsEAAAAAAAAAAoiMEoAAAAAAAAAACkIRjBKAAAAAAAAAAApASCw0agCIsLGHTApB1v//////v///1v+////AAAAAAciBzAwBAwMISEFIQUEAAAACQBwAAgJAAQJAJkACQAAACFAAAAFKTABAAAAAgAAAABfMVv//////v///1v+////AAAAAAciLSkAW/7////+////W/7///8AAAAAByIHWwQAAAAAAAAAWwgAAAAAAAAACiIwSgAAAAAAAAAAKQhGMEoAAAAAAAAAACkBILDRqAIiwsYdMCkHW//////+////W/7///8AAAAAByIHMDAEDAwhIQUhBQAAAgAAAAiQAACZABkRAMBhW//////+////W/7///8AAAAAByItKQBb/v////7///8AW/7///8AAAAAByIHWwQAAAAAAAAAWwwAAAAAAAAACiIwSgAAAAAAAAAAKQhGMEoAAAAAAAAAACkBILDRqAIiwsYdMCkHW//////+////W/7///8AAAAAByIHMDAEDAwhIQUhBTEAAAIAAAAJAAkAmQAZEQHAeVv9/////v///1v+////AAAAAAciB1sEAAAAAAAAAAgIRjBKAAAAAAAAAAApASCw0agCIsLGHTApMAgtKVv9/////v///1v+////AAAAAAciB1v+/////v///1v+////AAAAAAciB1sEAAAAAAAAAAgIRjBKAAAAAAAAAAApASCw0agCIsLGHTApB1sEAAAAAAAAAFsEAAAAAAAAAAwiMEoAAAAAAAAAACkIRjBKAAAAAAAAAAApASCw0agCIsLGHTApLSkDAAAACQB5AAkAmAAJAAAAAAAADTAEMAoqKQEAAAAGAAAAAAMBAQAAAAEAAAAAETIBM1sEAAAAAAAAAEIIKSAAAAAAAAAAAAEAAAAIAAAAAAcIKQcBAAAAAwAAAACLCFsIAAAAAAAAAEQIKQgxBwgwBEAIASAAAAAAAAAAAAcIM1sCAAAAAAAAADAECDAPDw8PDw8pKQgBIAAAAAAAAAAARikKWyAAAAAAAAAACEIBIAAAAAAAAAAACghbAgAAAAAAAAAwBAgwDw8PDw8PKSkIASAAAAAAAAAAAEQIKTIyJgIiIgIAAAAJmZAICXkAAAAATVv9/////v///1v+////AAAAAAciB1sEAAAAAAAAAFsEAAAAAAAAAAoiMEoAAAAAAAAAACkIRjBKAAAAAAAAAAApASCw0agCIsLGHTApWzEAAAAAAAAACC0pW/3////+////W/7///8AAAAAByIHW0QAEQAAAAAAWwQAAAAAAAAARghbsCa2l827LQ8fKQACAAAACQCQBwkAMBAAgDFb4e4KotyZc1YfKVsEAAAAAAAAAAoIRjBKAAAAAAAAAAApASCw0agCIsLGHTApWwEAEAAAAAAACkAIKQgtKQAAAQAAAAmQQBHAD1v9/////v///1v+////AAAAAAciW/7///8AAAAALSkBAAAABwAAAAAHW7AmtpfNuy0PHykBAAAAAwAAAAAHW+HuCqLcmXNWHykBAAAAAwAAAACpW+HuCqLcmXNWHykQMQoIWwQAAAAAAAAARghbsCa2l827LQ8fKQgBIAAAAAAAAAAALSlb4e4KotyZc1YfKVsEAAAAAAAAADIiMEoAAAAAAAAAACkKCFsEAAAAAAAAAEYIW7AmtpfNuy0PHykIASAAAAAAAAAAAC0pW+HuCqLcmXNWHylbCAAAAAAAAAAyIjBKAAAAAAAAAAApCghbBAAAAAAAAABGCFuwJraXzbstDx8pCAEgAAAAAAAAAAAtKVvh7gqi3JlzVh8pWwwAAAAAAAAAIjBKAAAAAAAAAAApWwQAAAAAAAAARghbsCa2l827LQ8fKQgBIAAAAAAAAAAALSlb4e4KotyZc1YfKQQAAAAJkJAACZAACQgIkAAFAAAAAAAAAA9bRAARAAAAAABbBAAAAAAAAABGCFuwJraXzbstDx8pAQAAAAcAAAAAN1vh7gqi3JlzVh8pWwQAAAAAAAAAWzwAEAAAAAAACkAIKQhGMEoAAAAAAAAAACkBILDRqAIiwsYdMCkHMDAKISEFAAABAAAACQB5EcA/W+HuCqLcmXNWHylbBAAAAAAAAABbPAAQAAAAAAAKQAgpCEYwSgAAAAAAAAAAKQEgsNGoAiLCxh0wKTAECC0pW7AmtpfNuy0PHykAAFvh7gqi3JlzVh8pAgAAAAkAmRADAAAAgAAFMCDpjUwBT57qjAEAAAACAAAAAB9bBAAAAAAAAABb/v///wAAAAAHIlv+////AAAAAC0pW0AAEQAAAAAAAFsEAAAAAAAAAEYIW7AmtpfNuy0PHykBAAAACQBgAAEJCCktKQEAAAAEAAAAAOcIWwgAAAAAAAAARAgpCDEwBEAIASAAAAAAAAAAAAcyB1sgAAAAAAAAADUCIlv/////AAAAADJbAgAAAAAAAAAwBAgwDw8PDw8PKSkIASAAAAAAAAAAAEYpMVv/////AAAAAEoAAAAAAAAAAAhCKRAmDAomNhJbAgAAAAAAAAAwBAgwDw8PDw8PKSkIASAAAAAAAAAAAEQIKTIyJgIiIggQDFsCAAAAAAAAADAECDAPDw8PDw8pKQgBIAAAAAAAAAAARikyMiYCIiIzBC0pCC0pAAAAAwAAAAkJCZAJmJAZCZkUEQAA4F1b4e4KotyZc1YfKTFb/f////7///9b/v///wAAAAAHIi0pAFv+/////v///1v+////AAAAAAciLSkAAFv9/////v///1v+////AAAAAAciB1vg////AAAAAFtAAAAAAAAAAAoIQikmMVv9/////v///1v+////AAAAAAciLSkAW0AAEQAAAAAAWwQAAAAAAAAARghbsCa2l827LQ8fKQMAAAAJAAkQCQCQAAkAAACAAAAZW+HuCqLcmXNWHylbRAARAAAAAABbBAAAAAAAAABGCFuwJraXzbstDx8pAAABAAAACQAQEcBbW+HuCqLcmXNWHylbRAAQAAAAAABACClbBAAAAAAAAABGCAgyBwhbCAAAAAAAAABECClbAgAAAAAAAAAwBAgwDw8PDw8PKSkIASAAAAAAAAAAAEYpCClb/wAAAAAAAAAmMAghBQACAAAACQAJCYkQAAAACNNb4e4KotyZc1YfKVv//////v///1v+////AAAAAAciLSkAW7AmtpfNuy0PHykAW+HuCqLcmXNWHykAW//////+////W/7///8AAAAAByIHMARbRAAQAAAAAAAKQAgpWwQAAAAAAAAARggxBzNbCAAAAAAAAABECClb/wAAAAAAAAAIWwIAAAAAAAAAMAQIMA8PDw8PDykpCAEgAAAAAAAAAABECClb/////wAAAABKAAAAAAAAAAAIQikIJgwMWwgAAAAAAAAARAgpWwIAAAAAAAAAMAQIMA8PDw8PDykpCAEgAAAAAAAAAABECCkyMiYCIiIILSkAAAAEAAAACQAIEAkACQQJkAkHCZkREYAAAOBhW/3////+////W/7///8AAAAAByIHWyAAAAAAAAAAQAgpMDAIWwAAAAABAAAAIyIwMAQIWwAAAAABAAAAIyJb2oiK5wAAAABbInpo+AAAAAAIWwAAAAABAAAAIyJb7ti7bQAAAABbOsjzvQAAAAAIWwAAAAABAAAAIyI0NRESCwwIDRAICluwJraXzbstDx8pAwAAAAkACQQJAAAJCAAAAAAAABkIKTEwBEAIASAAAAAAAAAAAAcIBwEAAAA5AAAAAP0IWwgAAAAAAAAAI1sgAAAAAAAAAAgCIggxBzIwBEAIASAAAAAAAAAAAAcKWwIAAAAAAAAAQAgBIAAAAAAAAAAABzRbAgAAAAAAAAAwBAgwDw8PDw8PKSkIASAAAAAAAAAAAEQIKQ0xWyAAAAAAAAAANUIpWwIAAAAAAAAAMAQIMA8PDw8PDykpCAEgAAAAAAAAAABGKRAyMiYCIiILNFsCAAAAAAAAADAECDAPDw8PDw8pKQgBIAAAAAAAAAAARAgpCFsgAAAAAAAAABBCKVsCAAAAAAAAADAECDAPDw8PDw8pKQgBIAAAAAAAAAAARikyMiYCIiIDAAAACZAICZkAmQmZCZAZAAAARVvh7gqi3JlzVh8pW/3////+////W/7///8AAAAAByIHWygAAAAAAAAAMiIwSgAAAAAAAAAAKVsIAAAAAAAAADIIRggpMEoAAAAAAAAAACkBILDRqAIiwsYdMClbBAAAAAAAAABGCFuwJraXzbstDx8pAAIAAAAIAAmQBxAAAAAIHQgpCDItKTAEQAgBIAAAAAAAAAAALSkBAAAAWQAAAAC2AghbCAAAAAAAAABECCkIDTERCzE0WwIAAAAAAAAAMAQIMA8PDw8PDykpCAEgAAAAAAAAAABECCkNWyAAAAAAAAAANEIpAFsCAAAAAAAAADAECDAPDw8PDw8pKQgBIAAAAAAAAAAARikyNFsCAAAAAAAAADAECDAPDw8PDw8pKQgBIAAAAAAAAAAARAgpMjImAiIiC1sgAAAAAAAAAApCKVsCAAAAAAAAADAECDAPDw8PDw8pKQgBIAAAAAAAAAAARilbIAAAAAAAAAASAiJb/////wAAAAAIWwIAAAAAAAAAMAQIMA8PDw8PDykpCAEgAAAAAAAAAABGKTFb/////wAAAABKAAAAAAAAAAAIQik2WwIAAAAAAAAAQAgBIAAAAAAAAAAAByY2BwomCzIyJgIiIjUEBC0pCDQELSkyMiYCIiIILSkFAAAACQmZEAmZkBkJkAgCCZkAmYkAAACAAAAAADlb4e4KotyZc1YfKVsYAAAAAAAAAAwiMEoAAAAAAAAAAClbCAAAAAAAAAAyCEYIKTBKAAAAAAAAAAApASCw0agCIsLGHTApWwQAAAAAAAAARghbsCa2l827LQ8fKQIAAAAJkJAAAQAAAAAARVvh7gqi3JlzVh8pW/3////+////W/7///8AAAAAByIHWyAAAAAAAAAAMiIwSgAAAAAAAAAAKVsIAAAAAAAAADIIRggpMEoAAAAAAAAAACkBILDRqAIiwsYdMClbBAAAAAAAAABGCFuwJraXzbstDx8pAAIAAAAIAAmQBxAAAAAIOVvh7gqi3JlzVh8pWxAAAAAAAAAADCIwSgAAAAAAAAAAKVsIAAAAAAAAADIIRggpMEoAAAAAAAAAACkBILDRqAIiwsYdMClbBAAAAAAAAABGCFuwJraXzbstDx8pAgAAAAmQkAABAAAAAAArW+HuCqLcmXNWHylb/f////7///9b/v///wAAAAAHIgdbEAAAAAAAAAAyQAgpWyAAAAAAAAAACkAIKVuwJraXzbstDx8pAgAAAAgACRADAAAAAAA/W+HuCqLcmXNWHylb/f////7///9b/v///wAAAAAHIgdbBAAAAAAAAABbIAAAAAAAAAAKIjBKAAAAAAAAAAApCEYwSgAAAAAAAAAAKQEgsNGoAiLCxh0wKQcwMAohIQUCAAAACAAJkAUAAAAAAE1b/f////7///9b/v///wAAAAAHIgdbBAAAAAAAAABbJAAAAAAAAAAKIjBKAAAAAAAAAAApCEYwSgAAAAAAAAAAKQEgsNGoAiLCxh0wKQcAW/7////+////AFv+////AAAAAAciB1tAABEAAAAAAFsEAAAAAAAAAEYIW7AmtpfNuy0PHykAAAIAAAAJAJAHCAADEUDAM1vh7gqi3JlzVh8pKVsAABAAAAAAADBKAAAAAAAAAAApWxBABAAAAAAALSkwMEoAAAAAAAAAAClbEUAEAAAAAAAtKVsAABAAAAAAADBKAAAAAAAAAAApWxJABAAAAAAALSkCAAAACJAABQMAAAAAAE1bAAASAAAAAABbsCa2l827LQ8fKTEwCFvvvq3eAAAAAA0IClsAAABAAAAAAC4NCAopKSkpW+HuCqLcmXNWHylbard16E5VRTFbLQaGR9NHENlbt7yjNo481zhbmY/caenzUXJblkHgLsLKoPcfKVsAAAQAAAAAAAAAWwQAAAAAAAAAW7AmtpfNuy0PHykAAwAAAAkACQUJAAAQBBAAAACBCB9bDAAAAAAAAABb/v///wAAAAAHIlv+////AAAAAC0pW0AAEQAAAAAAAFsEAAAAAAAAAEYIW7AmtpfNuy0PHykBAAAACQBgAAFdW+HuCqLcmXNWHykxW/X////+////W/7///8AAAAAByItKQBb9v////7///9b/v///wAAAAAHIi0pAABb9f////7///9b/v///wAAAAAHIgdb4P///wAAAABbQAAAAAAAAAAKCEIpJjFb9f////7///9b/v///wAAAAAHIi0pAFtAABEAAAAAAFsEAAAAAAAAAEYIW7AmtpfNuy0PHykDAAAACQAJEAkAkAAJAAAAgAAA01vh7gqi3JlzVh8pW/f////+////W/7///8AAAAAByItKQBbsCa2l827LQ8fKQBb4e4KotyZc1YfKQBb9/////7///9b/v///wAAAAAHIgcwBFtEABAAAAAAAApACClbBAAAAAAAAABGCDEHM1sIAAAAAAAAAEQIKVv/AAAAAAAAAAhbAgAAAAAAAAAwBAgwDw8PDw8PKSkIASAAAAAAAAAAAEQIKVv/////AAAAAEoAAAAAAAAAAAhCKQgmDAxbCAAAAAAAAABECClbAgAAAAAAAAAwBAgwDw8PDw8PKSkIASAAAAAAAAAAAEQIKTIyJgIiIggtKQAAAAQAAAAJAAgQCQAJBAmQCQcJmRERgAAA4N1b7ti7bQAAAABbOsjzvQAAAAAIWwAAAAABAAAAIyIxW/j////+////AFv+////AAAAAAciLSkAW9qIiucAAAAAAFsiemj4AAAAAAhbAAAAAAEAAAAjIjFb+f////7///9b/v///wAAAAAHIi0pADAwBAhbAAAAAAEAAAAjIjFb+v////7///9b/v///wAAAAAHIi0pADAwCFsAAAAAAQAAACMiMVv7/////v///1v+////AAAAAAciLSkAMVv8/////v///1v+////AAAAAAciLSkAMVv9/////v///1v+////AAAAAAciLSkAW/X////+////AABb/v///wAAAAAHIgdbIAAAAAAAAABACCkzMzQ1CwwIChESFxoIDRATFBUWCFuwJraXzbstDx8pAAUAAAAJAIAACQCABAmQAEAIkAAQCZBJECEAAIiARVvh7gqi3JlzVh8pW/X////+////W/7///8AAAAAByIHWygAAAAAAAAAMiIwSgAAAAAAAAAAKVsIAAAAAAAAADIIRggpMEoAAAAAAAAAACkBILDRqAIiwsYdMClbBAAAAAAAAABGCFuwJraXzbstDx8pAAIAAAAIAAmQBxAAAAAIRVvh7gqi3JlzVh8pW/X////+////W/7///8AAAAAByIHWyAAAAAAAAAAMiIwSgAAAAAAAAAAKVsIAAAAAAAAADIIRggpMEoAAAAAAAAAACkBILDRqAIiwsYdMClbBAAAAAAAAABGCFuwJraXzbstDx8pAAIAAAAIAAmQBxAAAAAIK1vh7gqi3JlzVh8pW/X////+////W/7///8AAAAAByIHWxAAAAAAAAAAMkAIKVsgAAAAAAAAAApACClbsCa2l827LQ8fKQIAAAAIAAkQAwAAAAAAOVvh7gqi3JlzVh8pW/X////+////W/7///8AAAAAByIHWwQAAAAAAAAAWyAAAAAAAAAACiIwSgAAAAAAAAAAKQhGMEoAAAAAAAAAACkBILDRqAIiwsYdMCkHMCEFAgAAAAgACZACAAAAAAALKSkwW97Ard4AAAAAAAEAAAAFAAAAAdVb+P////7///9b/v///wAAAAAHIgdb+f////7///9b/v///wAAAAAHIgdb+v////7///9b/v///wAAAAAHIgdb+/////7///9b/v///wAAAAAHIgdb/P////7///9b/v///wAAAAAHIgdb/f////7///9b/v///wAAAAAHIgdb9f////7///9b/v///wAAAAAHIgdbBAAAAAAAAABbJAAAAAAAAAAKIjBKAAAAAAAAAAApCEYwSgAAAAAAAAAAKQEgsNGoAiLCxh0wKQcWIjFb/v////7///8AW/7///8AAAAAByItKQBb9f////7///9b/v///wAAAAAHIgdbIAAAAAAAAABACCkwOSI5FxoIGx4IHhoKGx4ICh4aFRYLDBMUDRAREhFbsCa2l827LQ8fKQAFAAAACQBgAAkAYAAJAJAJCQAJmTkQAAAAAEAACDtb4e4KotyZc1YfKVv1/////v///1v+////AAAAAAciB1sEAAAAAAAAAFsgAAAAAAAAAAoiMEoAAAAAAAAAACkIRjBKAAAAAAAAAAApASCw0agCIsLGHTApBzAhBTECAAAACAAJkAMAAAAAAAVb3sCt3gAAAAAAAQAAAAIAAAABG1v2/////v///1v+////AAAAAAciB1tAABEAAAAAAFsEAAAAAAAAAEYIW7AmtpfNuy0PHykAAQAAAAkAMBCAEVvh7gqi3JlzVh8pW/7////+////W/7///8AAAAAByIHAQAAAAgAAAAADzAEMAwqKQgBAAAABwAAAAAHMAohAQAAAAMAAAAABykwIOmNTAFPnuqMAQAAAAMAAAAAD1v1/////v///1v+////AAAAAAciW/7///8AAAAALSkBAAAABwAAAAAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAAwCwAAAAAAADAFAQAAAAAAMBEBAAAAAAAwpwEAAAAAADA+AgAAAAAAMBYDAAAAAAAwJgMAAAAAADAxAwAAAAAAMFMDAAAAAAAwYAMAAAAAADD0AwAAAAAAMJEEAAAAAAAw2wQAAAAAADAEBQAAAAAAMBkFAAAAAAAwLgUAAAAAADBTBgAAAAAAMHwGAAAAAAAwyQYAAAAAADAvBwAAAAAAMEMHAAAAAAAwjAcAAAAAADCaBwAAAAAAMIEIAAAAAAAwMwkAAAAAADBpCQAAAAAAMN0JAAAAAAAw7woAAAAAADCTCwAAAAAAMLELAAAAAAAwuwwAAAAAADA8DQAAAAAAMFwNAAAAAAAwwA4AAAAAADArDwAAAAAAMKwPAAAAAAAwFxAAAAAAADBrEAAAAAAAMNkQAAAAAAAwbhEAAAAAADDeEQAAAAAAMIASAAAAAAAwyRIAAAAAADB7EwAAAAAAMI0UAAAAAAAw2RUAAAAAADBaFgAAAAAAMNsWAAAAAAAwLxcAAAAAADCaFwAAAAAAMLEXAAAAAAAwARkAAAAAADBtGQAAAAAAMIEZAAAAAAAwwBkAAAAAADDqGQAAAAAAMPsZAAAAAAAwCBoAAAAAADAdGgAAAAAAMAkAAAABAAAQDgAAQAMAABAAAACABAAAABsAAIAGAAAQIgAAQAgAABAlAAAACQAAEAMAAEALAAAAAgAAgAQAAAAEAACADwAAEEAAAAACAAAAQQAAAAMAAAAUAACAEAAAAEMAAAADAAAARAAAAAMAAABFAAAAAwAAABQAAMARAAAASAAAQA8AAAAKAABAEgAAAEoAAMADAAAASgAAQAUAAABMAADACgAAAEoAAEAGAAAATAAAAAcAAABKAABABwAAAEsAAAAIAAAATQAAwAgAAABOAACACQAAAE0AAMAJAAAATgAAAAoAAABMAACADgAAAE8AAMANAAAATQAAgAwAAABNAADADAAAAEoAAIALAAAATAAAwAsAAABLAABADAAAAFEAAIABAAAQEAAAgBQAAAAXAADAFAAAAB8AAMAUAAAAEwAAABUAAABWAABAFQAAAFkAAAAWAAAAWwAAgBYAAAAwAADAFAAAADsAAEAXAAAAXwAAgBcAAABgAACAFgAAAGIAAEAYAAAAXwAAwBgAAABkAADAAQAAAAQAAEAZAAAQGAAAgBkAABBnAAAAAQAAEBgAAAAaAAAQawAAgBoAAABsAAAAAQAAEG0AAEAOAAAQbwAAgBsAAABvAABAHAAAAHIAAIABAAAQcwAAwAIAAAB0AACABQAAAHUAAIAHAAAAdgAAgAoAAAB5AAAADgAAAHgAAIAHAAAAfAAAQAEAAAB+AADAFAAAAH8AAMAVAAAAEQAAACAAAAA8AABAIAAAAIIAAMAVAAAAfQAAwCAAAACFAABAGgAAAIQAAAALAAAAiAAAABwAAAARAABAIgAAAHcAAIAiAAAAiwAAgBEAAAB7AAAAIwAAAI0AAEAKAAAAEgAAwCMAAACNAAAADQAAAJEAAAAXAAAAkwAAABcAAACGAAAAJQAAAIcAAEAlAAAAlgAAgCMAAACXAACAHgAAABMAAAAmAAAAmQAAgA0AABCaAACAJAAAAJsAAEANAAAAAQAAACcAAABQAABAJwAAAJ8AAEAlAAAAPwAAACgAAAChAAAAJAAAABMAAIAoAAAAowAAgCQAAAABAAAAKQAAAIJC7dY0lrAsK4nNssLqfcKjTFqpd9IDftT9JCKhVkora5Cn9xbN/LWdR+xUkM081e5y9VXyU0r16+dYZ9/b3VivvBiZs2ZGMcd3J5YTtSbyrZd1/y4GSJxqj+6IGLpAxbl3ehi6nGG1R4H1qKxotRKyWnAkdk3K+sgn7lar+dXqNvifebmoMVsISw/mTxeF43x2UI3oayzo4oGJobbzeCekVx42T/7WlRXAHUHitM+93qpXH0hciQDPYOr/E42F9AjkL+RlIjU6UiPKbobAZFYCMiMzrbw/vVE4JTC0jWBLWg8UCT1u/jgsZBRGr34ngbDizOQjRkMHPBZvGPKMcRri6IH3JHAsYAJHSHikulKISC+iie8uOgoxw76V4/XpOdqjokkSHtGBv754i4IdrcodkcGQy94Wuc2nchWUPWTXcWLZWYLbkKqi4FqUtwhV7vr/H6LBf6qyIlSukvD4W9UceBr+4dk/8ukMhW4gG9JeCxGcUAJSlTeUz0Cq6uVLjvWqGklf802O3rBjUjwf0wSNwy07HY8MMJyjRE+FwfACKbJ2BYNNeFD7jKL547cFZpmcHWPYUOuKeDTxKuVIwbDvzhAJ0tBpFXMX0h88FE/uzyWgqj9h/isS7jX2TaaDFEjiiDiMyMzs4g54OVWPzW5QTuU97m3sbxNUvog1QWewPQHxAv3tpkGbG0Z3YLBJZSLgtfn73cUf7oMqQj51sRm+TNSlELAd0CSmdaU22I1NRAsWfx2etPnD6DSEdwklsVyEJcToBoVIOc49OvbHj+yMoZzDDRGmfN5X5HBWc5KavRb8XCzfKsiiLAf72R2bG+BBApqaj7jzN5cdhBg13ug0iWpCvuH3rJYQeKfuMJMR4yQ8nNnLsM4ezzuGLTY6X2mTBGmZ+6QOfBH7qqNYY7rQpCtTX07Osjwuy+lpgusns6AvYmUnVD89gy4ahdM/ZcisWaBRsg5uusg0yRLsuTphP145Kak8KoO/xF1caXhifWRL/p7uae/Y3lSFO72xGtf0SFqy99Ggs73hhs9GIiLXCWIzXuroqtXd2fhlgaBhiqn4LQPZ1hPBCC//3G7pmmh13YKTLIRniRU5zYlarFbGqEgz5cR8c0I1mNa7q8AFF2/P0TzVDmSdfNV3BF8zgCzzE5hyRrxKnOvK3zMzgllFjVhm0ar3gY0Nr+F1ucHit4Z/x8x9wCKGVpPLvp4O7kOd06YrT99WgnGJKYJETL5jKGgioBVOfNBivLppPj7sVn9OXe/E61L/0HKY6kci3RYsr4yVBbU5QA/MI6nTYWa23+NLlV4IWRQqJQhTa0qmsLwwIDl94sDCPPg/Gn/CtmHoob8/Z7hOtAayWQiV7KNHHRXUFJh7zqabpl3rFCWuMe5ZfqVnvPSgAswUHFbiqY2VOfg+JZQxXp3YHpk2NAsf1uISXEE6IPgZ2/qM/CAeB7O3c18dINUSDA+v4PEnQfCtJOGmeJv81cO8gK6OS2/hNKCf3ZAOIb9Gm1px7LjDRmvfzkFgouIQM6gCnMnX/hM4O9N4SUCfkkryeeJOHfyRr1bNoFiUQ5uefU9LciY783FiryePNrMrgySEaTcc4le8BF6JK0ETi7+TUGNwihdtm70bkt9RMrDr0pR1+fXkSntrTgBGnDMzF5unumNyNW2vdceQTfifjHwVkLSEYk551xvVIcKioJKJaXJQi5nDsB5maSWcZ88KJ8xAo254sbi3Y85TSW/g/d69MLng7KszfO66oa3pDh5PE5I01TiONH9CGDCXjSdmgpHrU4IAnTUgDkDl71BXd2s00EsC4Y2HoIeIzW7zjoGRgiOdHKc+dtxlAYm96UCCxxW1QtU88BKKip98w0gAdHVl6wbwjP03Ze0RGg+i5Tn4tl8hRpduGxEArv6OeNRAhfzgNefETvbkP3LMxoHsm2f83nhVzDBO/3cY7IUdJGceFwlQ8YLJBxmFGcuCAb5AZWxUQ8Bp/eek52Ye2b2+Ox6T1autgeMBEO9SQxwU0v/ppCIckM2LpJklym3FytFPnPqqoHZu72rTZYG9Xe+M9G8+Ng8dxtQNkH3K/UGlPoT10QxB/EUArukx1KcHMcYkTnoE4i6E1mYmQoStO92L2UIFTlS3pmCyGO7+e5mkoCUC0+MJZXJBbNnPBG9S/AtyZqD2BAbzveYJKbgJ+c06hBdqL/EdC3XF9SV0AZygnqzzC7m7v51ueDB03MnzxY/2RABorhRcxgBjZgNe+R0UOdMG+yIUg22AxPYx/u4LD2MhJ+IgzjLo+Yb9qS8ux59uEcibw19b0yDQCMDQ4TGvpQ3SN80AYX1FuvGV/yDlbfgXM6Pho+y1+LrjOpc2oLOIPt1QASWho5ZP4DZE2j4TXvqnvG3qkgyXae7tUrhzUBfEBaX/6KmIKDNyl12T/Pne+lDg1kPhpMBWaHzcSsOTGXiEECteHqXmAWHW5X+zh72x5hVitHr98/gKzrwFzS/dk95NSSVUOXErPU7b3VvLICiba0iXiGESrDaPEiuWYYVRFSkwx9IUEHVvVE64wIYew+/OIg6eeiQ6VxachvApYUf4h6iPlDf4TUbQ6a+YjnC8OLTR+eN7Pw23cd1vGGV+gi4DGjX02InTXkaG4uBNAgbJ0ABb+8LQF+TXtoRlhPL0vsZRmx6iA+s3DGLgZN5wQBdDQUrpk8pLBKJJECai9EubQVQJ2R1GUlD/o3+d4QLDBrPClJRpOcddDF4BZrcBDygJHWUGk6fTDzEF47q8Y86pbaI0+xNLt6e2+EGZTi3iHvdn0OZsfK3LJPs3zrIHctUW0JCB5iN245zRRi2wXrQO8ZMubCa0SwWQ+xNX4ZCi7n0ja5AhgIz1b2M7bF/8a2IXTWYJP2SwhwrmaO6sagRslDhU7HEx2VCSnP7/GQcVtc9FTYXFAhwHitaVhuglcoh1j8b+wXpN/+rtKy/riEvUpOJJ3FfxvlBQ4lt9DLDUI2sMmnZQq+oa9pyAzivAUnspGnMFakhMFTYXW+1Ec4vCMJ0XUXhbD/0+E83oQ6OVBhaI7ydsXqwgdkPwp7O+71P6sz9bAKqdq8S6no5cfVHy5K9nVDQh6u/B4jepCsAZKsj8lpSekdpuZq4+u55TZQeHjmUciv6dCEHBBFsm37W1yU6HwuRxuurLTSlOMc4+ZSNxlYpdDmU7KTWbI+J4DKp5l9LXgsBB3Kc0N1yrRhVCdWvMtazCT1k+XtU2Rht0oG72HK04tpH20eHt3l9T4URYY/G+nlkvlhhSoJmMO3jJ0S1OwFUr02EABxSgrSJTHzPeqdnP3FaE2pztrQS461vFmuGwDUawoKbigXDq1UroNqf/E+vZ4eKDQso443lwRAWvoD3JmS6ZY8uOlgvTKMYB+02HFhEENq/doMHLlrL7Xdctpppm2Mqz+jbfQz8rlbe9fxkD9YIjfiCG9p9CKgjOX3Je9UZMjHrpwFbpKMYDlKLmYELy7u9VEOWDVwO6AvLtdBjLgfYXp30VAsNLrg8nI17BLfTLkuGbJ2lTCHNTxH7Ia02lv4TskLFeX3M3qlwEHcCXS6PLrM510Yb/6cGQXD4Pb2OfITrF2VdHeeTo9G2iEUssFRiGiOUBeuKOJ2FMTLpvARZtb/uFe2FTglaTHF0dwv4Iu15HqJ+ePHB1Y3LR3cY1hgKKrx92vlCRiuuKoFPdZSffG42qssu2roct4oZpbFGa+Pi8UvmX71AQGjFzNF2DNQ4fnQiSzSOVQS0j7v5jpLivdjgXWMBpwHlqPeMTEQGNHRoYzaYvgsPSwH3wtU94uIA7FoPubGKUldCISMDE4nLgeeDNofZeQdi3SW2T+VsF9Ql9WjF/wGx92Ge4rDy7MjohRR1+w+207vowwK6S2ZWmPmsOIUSw886Z7fbF7iZBJxvnzORTx7tyXeGkiTQzGngOQ6ewTXKC9/xAfMuNZQy3PnYAvLEcRMCH/83s7wLBHs5cs721bkSC61S3Khgp1dttL1QKx/FCshyS93l5HBEaTx1TVdgptJurzaOVklT1OMOaBJsup1z0IHYL2AD9YuYADTREPlI9vd9mO6zUK9FvW6THiBgODw5tIoWrfsYSCD4o+2YaDluLeKalPhDQ1NMeLHFpfxTM/VntUgdJdUbl/yMWTX1X06KeuvD2o+pe4OIxJCRAcqfHz/d8OMG3VhtD1MZlpr3cd9LnBh73Zg8/VfOpk77f7yrxD4QDLsQm1EvwedknpOHvPhHiYrrtvth5u6S+Qy5HrHtSSVYnZHl7BLhDpuH+TLbR7EsfWbL01thOSNomCuvoMD+/xz9fzm2h2TyeEQXhB4oerCXaWWZ9JitPnHCsG5T6VoVU2FiGsLAZIuqmCfDK8HleHdtC82FhWS6eMsI89TQL3Z0fDAwyHwoOAPNY8icg5E+Ym0f1fI67TKQk/6C8rICpYsBSonXXeDmGBX7NtLYw3nD95qeV9V40EiZbiFlprnblpiKiXnnFawMk0NyZW4ZBn68pW+Hc/secV5D1gdOiiU0Knnef4lyvEJcxmKA0A95AdZARVWv/G5hcNmoHN3l3TV6XmfXwv2KpdaOU86fur5FOAgmZeHApZekA/HAncBSMfZV2ax3J3E8khNhAUiG2gr/KV8FpAT1SwIihtHAzS2McsCY6hzUSNTQxNn5nmv8r30HzkIIvQZvMle/qX9ldyGBrjfRAWLzzNU3i/NJC8xkatGXli30VNMUNnPJ3nvJ3j2/qKGUTyYTxfqGUQDjHsi/MHaTYd+zUQfA/OI6khqobStMFTficBimp6Hluuq2pDcS7m20YgxidXfS1ZrPO2iwSn9PIoxx937+h+1HM8WPeU36gaRYqTXAby4DgkLyU/vXmQ3wHKvqwfefAGqabaJdbfc7JsKj6fRFLwF5AuJrTB7DGt9bUdvY1eH4SjadDV4CrmlHu5Ucur8dNtn9Hl8HDCgjzSQPH9KSxppVhDKQGt4zJAKgIlYjdKpxIiiXAR6nfeENkzD8tSmUqJqxqD769VXPUcux6AoJLUPgZQyupNHML08SKUXkt7HHPFjsn92bqYgd2m5lzU8ZQ+Q5LoZEH/nUB5UlXvSHRIix9hiWlnYEm+oMamAzC9nnBVpz8ThH+lsxlbRLC3KnLclfTtoslytRRBCKWiV5uehKSkCND6XO08XyCbgMAny/dfG/4eblvw2E6WsjIR84NW5EBawJTAzM1yB9pFQ6CQEBiF+hmjUPwPZJqz/XE+zLdDGBdEs49twZjQfLprOvQDZVQIFb8P9oNURoCQWfppxdBf9CicFDNtg2hVf6YYKtGluyPzo/8ofd+Rn/tiDiwDzD02yWx2+axrutQyBrfwnQeOistIQuxXkVGXg3IPQc40L+N9F473Sa0gBXGLpbyI2OpmxfhvFlUOi0NuDrbOEqHfQtlIFMYqJZJ9dCBw6xChWHrGoLNiKIQ2WECrNUamVQAlIOTwESFkJtBHnSyzegbRtlhU8laqbHYIa/5cmiNSEhnyseiNy5j4/BbC5AIkmIH04tWpRy/UpfEfMXqd8uMeHsu1OQybbM5HWL938958vu1PQGP3FNeQdvnnJp/Z93QC72rsy8+YLGnfstdzQ64S5brEfk3dnxUFJipqeMeyCYIgV+ABusTnej12gaFI9IRVxoV8ZBSwqHOf3vzEWhT3yGkLXFg0EoLFf9MGzrfSyJPuSUXSh2mF8Kl72Dodn52fuLqwAHMXauDBX1//2k9YHzWT41vzpXqGUAl8pG2OltnxNgJ9JStt7JSGlLqT2aEAH5cCd4ItH7UzkJtXPPyGPWvCjg7jHWLKbqj4D1o/J+sWhx994jgMUWfwR1K1JPhsw6CZaIsMizm2C4j/F51zy/Qv9m0Vd1dCmxGaGTDHyasjjZhPwlSYebn08WCmKzPAn44iUeO8jxt/E9WGz/dT6Dl0gtb/hocln/e2qzdMAdCd3xOGOoTF4YVgn5dkwncWdStMUp+h0cf2xxl4/R+ftbgjyhaAe1p2qyRbBrZ+Ol4Gv3UREpg5neFUjj3fyZhfR4uuyYk70/w6+qvlg8uPYrXiuJ1KGlghenAP+HDh0YGIAhk/jeQ7n4AeT0cLMlq4BKHUWtNjQBzdbrXPXEqsNlSaM1BLD4kCRAcUz/lIxZ9Xm27E41ZHTa7qxzmOwJ7E4J1Tx3dQBPVlYQnb8M7/MOZJvummhXWWNzt+0gH6FEoC/pOM8OBFe/Ghwhf7U8fcKvIHBP70KdyMn+EOqdmAweQUTyTBzH9xP6xwrrlmdMQsJLJclksHmcKpJtUQlxSFHy3ViZViSpunuJgiFTPrvXQPGnXCeRfMbKvZZTnJebNkGOrlBrain0Y7izPPNEp0SW8noKD7H8ECnP1K02Z1l+DRx8wIg70gt/8kNxP+fXfpUxss47I0lcjXixwgGiMrP8Y5yK5EQYgDcWdjxppZgoN0Q7LbJS2bdlB0e6zJhLm8J1HJAHbBW9S1rKjP211wt/TWV06Pyc1AROuBZ7n5ni/81tGPtOd+dgzTjyb5PX9J7N8sB1Y6g9F0/A8/N1g3kVOAEKPM8etcLAYkTAAKWMc+tSqksr0WW1X/C1yO9F4GqAEnpU3+a90hE8lPUgoDBsyz7gceSxy1ZrS5j+A7cAp35gPIEoulZIKP3jWx5FwE5vvVHaxYJ82ig1Wp0uiLDgi0PNVnqo64Pz+93VITXBwTa9qNgVX/3Vuqa7LKW09gbcwvAKnNa/7Vi9tOZ7hqKPGm+w7COb5Vp7aRCPoZ+inCMP2yxXhmar9tO8kbegs5/3gkmuXy428Ri72cHQo7CN9WcY7kSc70GG7nF6GPtIEwcrTNHik0am3qenGmr1mMrm1k7IC7ypyx3mfcfxa/B6GasicLTH2lCckP5QPPaRGyFNrHTEABceoWPj5Usb6FGE1GF0SpumDxOmBCUB2diJDDqGlyA1L8IHW2W1dTFVYNdJjOfjr71M8/dyivi4h6AhUFIls25VD0qtiDm+R0RoADVbSk34+HSZOuR6UlNhzpaQNTdvRAlk2AbAMJA20LbhE7T41LCCDoVQnTX/6eJ/ogLLbrIpSrz8oC6e0TzgYA5mP3Gnp81Fyt7yjNo481zgtBoZH00cQ2Wq3dehOVUUxIQBleHAAAAAAZWN0ZQAAAABkIHplAAAAAHJvIHAAAAAAYWRkaQAAAABuZyBpAAAAAG4gdGgAAAAAZSB0cgAAAABhaWxpAAAAAG5nIHQAAAAAaHJlZQAAAAAgZmVsAAAAAHRzAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAABwE9ADo6Im1pZGVuOmNvdW50ZXItYWNjb3VudC9jb3VudGVyLWNvbnRyYWN0QDAuMS4wIjo6ImdldC1jb3VudCIBngAAAAG1AAAAxpvsOwjm+Vae2kQj6GfopwjD9ssV4Zmq/bTvJG3oLOcBAwEDEQFBbWlkZW46YmFzZS9jb3JlLXR5cGVzQDEuMC4wL2ZlbHQAAQELaW5uZXIPAwAjYWNjb3VudF9wcm9jZWR1cmUBQwA6OiJtaWRlbjpjb3VudGVyLWFjY291bnQvY291bnRlci1jb250cmFjdEAwLjEuMCI6OiJpbmNyZW1lbnQtY291bnQiAaUAAAABWwEAALhE7T41LCCDoVQnTX/6eJ/ogLLbrIpSrz8oC6e0TzgYAQMBAxEBQW1pZGVuOmJhc2UvY29yZS10eXBlc0AxLjAuMC9mZWx0AAEBC2lubmVyDwMAI2FjY291bnRfcHJvY2VkdXJlATYAOjoibWlkZW46Y291bnRlci1hY2NvdW50L2NvdW50ZXItY29udHJhY3RAMC4xLjAiOjppbml0AY8AAAABrgAAAIdRa02NAHN1utc9cSqw2VJozUEsPiQJEBxTP+UjFn1eAQABAQEDMAA6OiJtaWRlbjpjb3VudGVyLWFjY291bnQvY291bnRlci1jb250cmFjdEAwLjEuMCIBCRVtaWRlbi1jb3JlAA0wLjI5LjRNNMhZZUwg3CHdbOt5KyFdEhCg6B1dZjaU8mXU8VRc/iNtaWRlbi1wcmVjb21waWxlcwANMC4yOS40p162ZrCye7nEZ56SlWUVvkEc5Nwd5or43SkfNcTzH7wdbWlkZW4tcHJvdG9jb2wADTAuMTYuMCRmU46znamWNGbNQssGotwJbQk2BiXHmrBdg8cxrTukH21pZGVuLXR4LWtlcm5lbAINMC4xNi4w9ZixC1EOPJNDQEMGvUnJqjhavMqIqQtx65prQiTefCIABzNwcm9qZWN0X3NvdXJjZV9wcm92ZW5hbmNlhwSc+1UVgPeTm76KnM8CLv/d7Hql2EA1H2BguT75ezHUpXa0pOVNnbSOOjokdxxkkH3dGzUxT1zAMaroA4pOFTyeAAE1YWNjb3VudF9jb21wb25lbnRfbWV0YWRhdGECAh9jb3VudGVyLWFjY291bnQBCzAuMS4wAQAsY291bnRlcl9hY2NvdW50Ojpjb3VudGVyX2NvbnRyYWN0Ojpjb3VudF9tYXABATljb3VudGVyIGNvbnRyYWN0IHN0b3JhZ2UgbWFwAAAJd29yZAAACWZlbHQAAAAAAAAAAAAAAAAAB3dpdJ4FCi8vIFRoaXMgZmlsZSBpcyBhdXRvLWdlbmVyYXRlZCBieSB0aGUgYCNbY29tcG9uZW50XWAgbWFjcm8uCi8vIERvIG5vdCBlZGl0IHRoaXMgZmlsZSBtYW51YWxseS4KCnBhY2thZ2UgbWlkZW46Y291bnRlci1hY2NvdW50QDAuMS4wOwoKdXNlIG1pZGVuOmJhc2UvY29yZS10eXBlc0AxLjAuMDsKCmludGVyZmFjZSBjb3VudGVyLWNvbnRyYWN0IHsKICAgIHVzZSBjb3JlLXR5cGVzLntmZWx0fTsKCiAgICBnZXQtY291bnQ6IGZ1bmMoKSAtPiBmZWx0OwogICAgaW5jcmVtZW50LWNvdW50OiBmdW5jKCkgLT4gZmVsdDsKfQoKd29ybGQgY291bnRlci1jb250cmFjdC13b3JsZCB7CiAgICBleHBvcnQgY291bnRlci1jb250cmFjdDsKfQo=",
      procedureExports: [
        {
          ...defaultProcedureExport(),
          path: '::"miden:counter-account/counter-contract@0.1.0"::"get-count"',
          digest:
            "0xc69bec3b08e6f9569eda4423e867e8a708c3f6cb15e199aafdb4ef246de82ce7",
          signature: {
            abi: 3,
            params: [],
            results: [{ Struct: { name: "miden:base/core-types@1.0.0/felt" } }],
          },
          readOnly: true,
        },
        {
          ...defaultProcedureExport(),
          path: '::"miden:counter-account/counter-contract@0.1.0"::"increment-count"',
          digest:
            "0xb844ed3e352c2083a154274d7ffa789fe880b2dbac8a52af3f280ba7b44f3818",
          signature: {
            abi: 3,
            params: [],
            results: [{ Struct: { name: "miden:base/core-types@1.0.0/felt" } }],
          },
        },
      ],
    },
    countReaderScript,
  ],
  components: [
    ...defaultComponents,
    {
      ...defaultComponent(),
      id: "counter-account",
      name: "Counter Contract",
      type: "account-component",
      scriptId: "counter-account",
      storageSlots: [
        {
          name: storageSlotName({
            packageName: "counter-account",
            traitName: "CounterContract",
            fieldName: "count_map",
          }),
          type: "map",
          value: "1:0",
        },
      ],
    },
    {
      ...defaultComponent(),
      id: "count-reader",
      name: "Count Reader",
      type: "account-component",
      scriptId: "count-reader",
      storageSlots: [
        {
          name: storageSlotName({
            packageName: "count-reader",
            traitName: "CountReader",
            fieldName: "count",
          }),
          type: "value",
          value: "0",
        },
      ],
    },
  ],
  tutorialId: "foreign-procedure-invocation",
};

export default state;
