export default `# mod miden:counter-contract/counter@0.1.0

export.get-count
    exec.::miden:counter-contract/counter@0.1.0::init
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::miden:counter-contract/counter@0.1.0#get-count
    trace.252
    nop
    exec.::std::sys::truncate_stack
end

export.increment-count
    exec.::miden:counter-contract/counter@0.1.0::init
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::miden:counter-contract/counter@0.1.0#increment-count
    trace.252
    nop
    exec.::std::sys::truncate_stack
end

proc.init
    push.1179648
    trace.240
    exec.::intrinsics::mem::heap_init
    trace.252
    push.[7028007876379170725,18060021366771303825,13412364500725888848,14178532912296021363]
    adv.push_mapval
    push.262144
    push.1
    trace.240
    exec.::std::mem::pipe_preimage_to_memory
    trace.252
    drop
    push.1048576
    u32assert
    mem_store.278536
    push.0
    u32assert
    mem_store.278537
end

# mod miden:counter-contract/counter@0.1.0::counter_contract

proc.__wasm_call_ctors
    nop
end

proc.miden_base_sys::bindings::storage::get_map_item
    push.1114144
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.32
    u32wrapping_sub
    push.1114144
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::<miden_stdlib_sys::intrinsics::felt::Felt as core::convert::From<u8>>::from
    trace.252
    nop
    push.12
    dup.4
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    push.8
    dup.5
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    push.4
    dup.6
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    movup.6
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    dup.5
    movup.2
    swap.3
    movdn.2
    swap.1
    swap.4
    swap.1
    swap.5
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::miden::account::get_map_item
    trace.252
    nop
    push.8
    dup.1
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    push.24
    dup.3
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    dup.0
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    push.16
    dup.3
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    push.16
    dup.1
    u32wrapping_add
    movup.2
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::miden_stdlib_sys::intrinsics::word::Word::reverse
    trace.252
    nop
    push.32
    u32wrapping_add
    push.1114144
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.counter_contract::bindings::__link_custom_section_describing_imports
    nop
end

proc.miden:counter-contract/counter@0.1.0#get-count
    push.1114144
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.32
    u32wrapping_sub
    push.1114144
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::wit_bindgen::rt::run_ctors_once
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.1
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.12
    dup.5
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.8
    dup.4
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.4
    dup.3
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    dup.1
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.16
    dup.1
    u32wrapping_add
    dup.1
    swap.1
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::miden_base_sys::bindings::storage::get_map_item
    trace.252
    nop
    push.28
    dup.1
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    push.32
    movup.2
    u32wrapping_add
    push.1114144
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.miden:counter-contract/counter@0.1.0#increment-count
    push.1114144
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.128
    u32wrapping_sub
    push.1114144
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::wit_bindgen::rt::run_ctors_once
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.1
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.12
    dup.5
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.8
    dup.5
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    dup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.4
    dup.5
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    dup.3
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    dup.4
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    dup.4
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.64
    dup.5
    u32wrapping_add
    dup.5
    swap.1
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::miden_base_sys::bindings::storage::get_map_item
    trace.252
    nop
    push.76
    dup.5
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    push.1
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    swap.1
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::add
    trace.252
    nop
    push.48
    dup.6
    u32wrapping_add
    dup.1
    swap.1
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::<miden_stdlib_sys::intrinsics::word::Word as core::convert::From<miden_stdlib_sys::intrinsics::felt::Felt>>::from
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::<miden_stdlib_sys::intrinsics::felt::Felt as core::convert::From<u8>>::from
    trace.252
    nop
    push.60
    dup.7
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    push.56
    dup.8
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    push.52
    dup.9
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    push.48
    dup.10
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_felt
    trace.252
    nop
    push.64
    dup.11
    u32wrapping_add
    swap.1
    swap.8
    swap.2
    swap.7
    swap.1
    swap.9
    swap.3
    swap.6
    swap.10
    swap.4
    swap.5
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::miden::account::set_map_item
    trace.252
    nop
    push.72
    dup.2
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    push.104
    dup.4
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    push.64
    dup.2
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    push.96
    dup.4
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    push.88
    dup.2
    u32wrapping_add
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    push.120
    dup.4
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    push.80
    dup.2
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    push.112
    dup.4
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    push.96
    dup.2
    u32wrapping_add
    push.16
    dup.3
    u32wrapping_add
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::miden_stdlib_sys::intrinsics::word::Word::reverse
    trace.252
    nop
    push.112
    dup.2
    u32wrapping_add
    push.32
    dup.3
    u32wrapping_add
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::miden_stdlib_sys::intrinsics::word::Word::reverse
    trace.252
    nop
    push.128
    movup.2
    u32wrapping_add
    push.1114144
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.wit_bindgen::rt::run_ctors_once
    push.1114148
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.1048584
    u32wrapping_add
    u32divmod.4
    swap.1
    swap.1
    dup.1
    mem_load
    swap.1
    push.8
    u32wrapping_mul
    u32shr
    swap.1
    drop
    push.255
    u32and
    push.0
    swap.1
    neq
    if.true
        nop
    else
        push.1114148
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_sw
        trace.252
        nop
        trace.240
        nop
        exec.::miden:counter-contract/counter@0.1.0::counter_contract::__wasm_call_ctors
        trace.252
        nop
        push.1
        push.1048584
        movup.2
        u32wrapping_add
        u32divmod.4
        swap.1
        dup.0
        mem_load
        dup.2
        push.8
        u32wrapping_mul
        push.255
        swap.1
        u32shl
        u32not
        swap.1
        u32and
        movup.3
        movup.3
        push.8
        u32wrapping_mul
        u32shl
        u32or
        swap.1
        mem_store
    end
end

proc.<miden_stdlib_sys::intrinsics::felt::Felt as core::convert::From<u8>>::from
    push.255
    u32and
end

proc.miden_stdlib_sys::intrinsics::word::Word::reverse
    push.1114144
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.16
    u32wrapping_sub
    push.8
    dup.3
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    push.8
    dup.3
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    movup.2
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    dup.2
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    push.12
    dup.1
    u32wrapping_add
    push.0
    movup.2
    swap.1
    push.1
    while.true
        push.0
        push.8
        dup.2
        eq
        neq
        dup.0
        if.true
            movup.3
            movup.2
            drop
            drop
            push.3735929054
            dup.0
        else
            dup.2
            dup.2
            u32wrapping_add
            dup.0
            push.4
            dup.1
            swap.1
            u32mod
            u32assert
            assertz
            u32divmod.4
            swap.1
            trace.240
            nop
            exec.::intrinsics::mem::load_felt
            trace.252
            nop
            dup.5
            push.4
            dup.1
            swap.1
            u32mod
            u32assert
            assertz
            u32divmod.4
            swap.1
            trace.240
            nop
            exec.::intrinsics::mem::load_sw
            trace.252
            nop
            movup.2
            push.4
            dup.1
            swap.1
            u32mod
            u32assert
            assertz
            u32divmod.4
            swap.1
            trace.240
            nop
            exec.::intrinsics::mem::store_sw
            trace.252
            nop
            dup.4
            push.4
            dup.1
            swap.1
            u32mod
            u32assert
            assertz
            u32divmod.4
            swap.1
            trace.240
            nop
            exec.::intrinsics::mem::store_felt
            trace.252
            nop
            push.4294967292
            movup.4
            u32wrapping_add
            push.4
            movup.3
            u32wrapping_add
        end
        push.3735929054
        dup.3
        dup.6
        swap.2
        swap.1
        cdrop
        push.3735929054
        dup.4
        dup.6
        swap.2
        swap.1
        cdrop
        push.1
        push.0
        movup.6
        cdrop
        push.1
        u32and
        swap.1
        swap.2
        swap.4
        swap.3
        swap.1
        if.true
            movup.4
            drop
            movup.4
            drop
            push.1
        else
            push.0
        end
    end
    drop
    drop
    drop
    drop
    push.8
    dup.1
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    push.8
    dup.4
    add
    u32assert
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    movup.2
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
end

proc.<miden_stdlib_sys::intrinsics::word::Word as core::convert::From<miden_stdlib_sys::intrinsics::felt::Felt>>::from
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.0
    trace.240
    nop
    exec.::miden:counter-contract/counter@0.1.0::counter_contract::intrinsics::felt::from_u32
    trace.252
    nop
    push.12
    dup.4
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    movup.5
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.8
    dup.4
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.4
    dup.3
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    swap.1
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
end

proc.intrinsics::felt::add
    add
end

proc.intrinsics::felt::from_u32
    nop
end

proc.miden::account::get_map_item
    trace.240
    nop
    exec.::miden::account::get_map_item
    trace.252
    nop
    movup.4
    dup.0
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.4
    dup.1
    add
    u32assert
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.8
    dup.1
    add
    u32assert
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.12
    add
    u32assert
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
end

proc.miden::account::set_map_item
    trace.240
    nop
    exec.::miden::account::set_map_item
    trace.252
    nop
    movup.8
    dup.0
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.4
    dup.1
    add
    u32assert
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.8
    dup.1
    add
    u32assert
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.12
    dup.1
    add
    u32assert
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.16
    dup.1
    add
    u32assert
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.20
    dup.1
    add
    u32assert
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.24
    dup.1
    add
    u32assert
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.28
    add
    u32assert
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
end
`;
