export default `# mod miden:base/note-script@1.0.0

export.run
    exec.::miden:base/note-script@1.0.0::init
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::miden:base/note-script@1.0.0#run
    trace.252
    nop
    exec.::std::sys::truncate_stack
end

proc.init
    push.1179648
    trace.240
    exec.::intrinsics::mem::heap_init
    trace.252
    push.[10058902622441936131,13054765064971916784,4422812840722442452,1742727163713970749]
    adv.push_mapval
    push.262144
    push.6
    trace.240
    exec.::std::mem::pipe_preimage_to_memory
    trace.252
    drop
    push.1048576
    u32assert
    mem_store.278552
    push.0
    u32assert
    mem_store.278553
end

# mod miden:base/note-script@1.0.0::p2id

proc.p2id::bindings::miden::basic_wallet::basic_wallet::receive_asset::wit_import7
    trace.240
    nop
    call.::miden:basic-wallet/basic-wallet@1.0.0::receive-asset
    trace.252
    nop
end

proc.__wasm_call_ctors
    nop
end

proc.__rustc::__rust_alloc
    push.1114212
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.1048664
    u32wrapping_add
    movup.2
    swap.1
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::<miden_sdk_alloc::BumpAlloc as core::alloc::global::GlobalAlloc>::alloc
    trace.252
    nop
end

proc.__rustc::__rust_dealloc
    drop
    drop
    drop
end

proc.__rustc::__rust_alloc_zeroed
    push.1114212
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.1048664
    u32wrapping_add
    dup.1
    swap.2
    swap.3
    swap.1
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::<miden_sdk_alloc::BumpAlloc as core::alloc::global::GlobalAlloc>::alloc
    trace.252
    nop
    push.0
    push.0
    dup.2
    eq
    neq
    if.true
        swap.1
        drop
    else
        push.0
        push.0
        dup.3
        eq
        neq
        if.true
            swap.1
            drop
        else
            push.0
            movup.2
            dup.2
            push.0
            dup.2
            push.0
            gte
            while.true
                dup.1
                dup.1
                push.1
                u32overflowing_madd
                assertz
                dup.4
                swap.1
                u32divmod.4
                swap.1
                dup.0
                mem_load
                dup.2
                push.8
                u32wrapping_mul
                push.255
                swap.1
                u32shl
                u32not
                swap.1
                u32and
                movup.3
                movup.3
                push.8
                u32wrapping_mul
                u32shl
                u32or
                swap.1
                mem_store
                u32wrapping_add.1
                dup.0
                dup.3
                u32gte
            end
            dropw
        end
    end
end

proc.p2id::bindings::__link_custom_section_describing_imports
    nop
end

proc.miden:base/note-script@1.0.0#run
    drop
    drop
    drop
    drop
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.48
    u32wrapping_sub
    push.1114208
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::wit_bindgen::rt::run_ctors_once
    trace.252
    nop
    push.16
    dup.1
    u32wrapping_add
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::miden_base_sys::bindings::note::get_inputs
    trace.252
    nop
    push.24
    dup.1
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    dup.0
    push.2147483648
    u32lte
    assert
    dup.0
    push.1
    u32lte
    if.true
        eq.0
        if.true
            drop
            push.1
        else
            drop
            push.1
        end
    else
        drop
        push.20
        dup.1
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_sw
        trace.252
        nop
        push.4
        dup.1
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_felt
        trace.252
        nop
        swap.1
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_felt
        trace.252
        nop
        push.8
        dup.3
        u32wrapping_add
        trace.240
        nop
        exec.::miden:base/note-script@1.0.0::p2id::miden_base_sys::bindings::account::get_id
        trace.252
        nop
        push.12
        dup.3
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_felt
        trace.252
        nop
        push.8
        dup.4
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_felt
        trace.252
        nop
        movup.2
        swap.1
        trace.240
        nop
        exec.::miden:base/note-script@1.0.0::p2id::intrinsics::felt::eq
        trace.252
        nop
        push.0
        push.1
        movup.2
        neq
        neq
        if.true
            drop
            drop
            drop
            push.1
        else
            trace.240
            nop
            exec.::miden:base/note-script@1.0.0::p2id::intrinsics::felt::eq
            trace.252
            nop
            push.0
            push.1
            movup.2
            neq
            neq
            dup.0
            if.true
                swap.1
                drop
            else
                push.28
                dup.2
                u32wrapping_add
                trace.240
                nop
                exec.::miden:base/note-script@1.0.0::p2id::miden_base_sys::bindings::note::get_assets
                trace.252
                nop
                push.36
                dup.2
                add
                u32assert
                push.4
                dup.1
                swap.1
                u32mod
                u32assert
                assertz
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::load_sw
                trace.252
                nop
                push.28
                dup.3
                add
                u32assert
                push.4
                dup.1
                swap.1
                u32mod
                u32assert
                assertz
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::load_sw
                trace.252
                nop
                push.32
                dup.4
                add
                u32assert
                push.4
                dup.1
                swap.1
                u32mod
                u32assert
                assertz
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::load_sw
                trace.252
                nop
                push.4
                movup.3
                swap.1
                u32shl
                dup.1
                swap.3
                swap.4
                swap.5
                swap.2
                swap.1
                push.1
                while.true
                    push.0
                    push.0
                    dup.2
                    eq
                    neq
                    dup.0
                    if.true
                        movdn.2
                        drop
                        drop
                        push.3735929054
                        dup.0
                    else
                        dup.2
                        push.4
                        dup.1
                        swap.1
                        u32mod
                        u32assert
                        assertz
                        u32divmod.4
                        swap.1
                        trace.240
                        nop
                        exec.::intrinsics::mem::load_felt
                        trace.252
                        nop
                        push.4
                        dup.4
                        add
                        u32assert
                        push.4
                        dup.1
                        swap.1
                        u32mod
                        u32assert
                        assertz
                        u32divmod.4
                        swap.1
                        trace.240
                        nop
                        exec.::intrinsics::mem::load_felt
                        trace.252
                        nop
                        push.8
                        dup.5
                        add
                        u32assert
                        push.4
                        dup.1
                        swap.1
                        u32mod
                        u32assert
                        assertz
                        u32divmod.4
                        swap.1
                        trace.240
                        nop
                        exec.::intrinsics::mem::load_felt
                        trace.252
                        nop
                        push.12
                        dup.6
                        add
                        u32assert
                        push.4
                        dup.1
                        swap.1
                        u32mod
                        u32assert
                        assertz
                        u32divmod.4
                        swap.1
                        trace.240
                        nop
                        exec.::intrinsics::mem::load_felt
                        trace.252
                        nop
                        movdn.3
                        swap.2
                        trace.240
                        nop
                        exec.::miden:base/note-script@1.0.0::p2id::p2id::bindings::miden::basic_wallet::basic_wallet::receive_asset::wit_import7
                        trace.252
                        nop
                        push.16
                        movup.3
                        u32wrapping_add
                        push.4294967280
                        movup.3
                        u32wrapping_add
                    end
                    push.3735929054
                    dup.3
                    dup.7
                    swap.2
                    swap.1
                    cdrop
                    push.3735929054
                    dup.4
                    dup.7
                    swap.2
                    swap.1
                    cdrop
                    push.3735929054
                    dup.5
                    dup.7
                    swap.2
                    swap.1
                    cdrop
                    push.1
                    push.0
                    movup.7
                    cdrop
                    push.1
                    u32and
                    swap.1
                    swap.3
                    swap.5
                    swap.2
                    swap.4
                    swap.1
                    if.true
                        movup.5
                        drop
                        movup.5
                        drop
                        movup.5
                        drop
                        push.1
                    else
                        push.0
                    end
                end
                drop
                drop
                drop
                drop
                drop
                push.44
                dup.1
                add
                u32assert
                push.4
                dup.1
                swap.1
                u32mod
                u32assert
                assertz
                movup.2
                swap.1
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::store_sw
                trace.252
                nop
                push.40
                dup.1
                add
                u32assert
                push.4
                dup.1
                swap.1
                u32mod
                u32assert
                assertz
                movup.2
                swap.1
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::store_sw
                trace.252
                nop
                push.16
                push.40
                dup.2
                u32wrapping_add
                dup.1
                swap.2
                swap.1
                trace.240
                nop
                exec.::miden:base/note-script@1.0.0::p2id::alloc::raw_vec::RawVecInner<A>::deallocate
                trace.252
                nop
                push.4
                push.16
                dup.2
                u32wrapping_add
                dup.1
                swap.2
                swap.1
                trace.240
                nop
                exec.::miden:base/note-script@1.0.0::p2id::alloc::raw_vec::RawVecInner<A>::deallocate
                trace.252
                nop
                push.48
                u32wrapping_add
                push.1114208
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::store_sw
                trace.252
                nop
            end
            push.0
            push.1
            movup.2
            cdrop
        end
    end
    push.0
    eq
    if.true
        nop
    else
        push.0
        assert
    end
end

proc.__rustc::__rust_no_alloc_shim_is_unstable_v2
    nop
end

proc.wit_bindgen::rt::run_ctors_once
    push.1114212
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.1048668
    u32wrapping_add
    u32divmod.4
    swap.1
    swap.1
    dup.1
    mem_load
    swap.1
    push.8
    u32wrapping_mul
    u32shr
    swap.1
    drop
    push.255
    u32and
    push.0
    swap.1
    neq
    if.true
        nop
    else
        push.1114212
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_sw
        trace.252
        nop
        trace.240
        nop
        exec.::miden:base/note-script@1.0.0::p2id::__wasm_call_ctors
        trace.252
        nop
        push.1
        push.1048668
        movup.2
        u32wrapping_add
        u32divmod.4
        swap.1
        dup.0
        mem_load
        dup.2
        push.8
        u32wrapping_mul
        push.255
        swap.1
        u32shl
        u32not
        swap.1
        u32and
        movup.3
        movup.3
        push.8
        u32wrapping_mul
        u32shl
        u32or
        swap.1
        mem_store
    end
end

proc.<miden_sdk_alloc::BumpAlloc as core::alloc::global::GlobalAlloc>::alloc
    push.16
    push.0
    push.16
    dup.4
    swap.1
    u32gt
    neq
    dup.3
    swap.1
    cdrop
    push.0
    push.4294967295
    dup.2
    u32wrapping_add
    dup.2
    u32and
    neq
    if.true
        dropw
        push.0
        push.3735929054
    else
        movup.2
        trace.240
        nop
        exec.::miden:base/note-script@1.0.0::p2id::core::ptr::alignment::Alignment::max
        trace.252
        nop
        push.0
        push.2147483648
        dup.2
        u32wrapping_sub
        dup.4
        swap.1
        u32gt
        neq
        dup.0
        if.true
            movdn.3
            drop
            drop
            drop
            push.3735929054
        else
            push.0
            dup.2
            u32wrapping_sub
            push.4294967295
            movup.5
            dup.4
            u32wrapping_add
            u32wrapping_add
            u32and
            dup.3
            push.4
            dup.1
            swap.1
            u32mod
            u32assert
            assertz
            u32divmod.4
            swap.1
            trace.240
            nop
            exec.::intrinsics::mem::load_sw
            trace.252
            nop
            push.0
            neq
            if.true
                nop
            else
                trace.240
                nop
                exec.::miden:base/note-script@1.0.0::p2id::intrinsics::mem::heap_base
                trace.252
                nop
                trace.240
                nop
                exec.::intrinsics::mem::memory_size
                trace.252
                nop
                dup.5
                push.4
                dup.1
                swap.1
                u32mod
                u32assert
                assertz
                push.16
                movup.2
                swap.1
                u32shl
                movup.2
                u32wrapping_add
                swap.1
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::store_sw
                trace.252
                nop
            end
            dup.3
            push.4
            dup.1
            swap.1
            u32mod
            u32assert
            assertz
            u32divmod.4
            swap.1
            trace.240
            nop
            exec.::intrinsics::mem::load_sw
            trace.252
            nop
            push.0
            push.4294967295
            dup.2
            u32xor
            dup.3
            swap.1
            u32gt
            neq
            if.true
                drop
                drop
                movdn.2
                drop
                drop
                push.0
            else
                movup.4
                push.4
                dup.1
                swap.1
                u32mod
                u32assert
                assertz
                movup.2
                dup.2
                u32wrapping_add
                swap.1
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::store_sw
                trace.252
                nop
                movup.2
                u32wrapping_add
            end
        end
        push.1
        push.0
        movup.3
        cdrop
        swap.1
    end
    push.0
    movup.2
    eq
    if.true
        drop
        push.0
        assert
    else
        nop
    end
end

proc.intrinsics::mem::heap_base
    trace.240
    nop
    exec.::intrinsics::mem::heap_base
    trace.252
    nop
end

proc.alloc::raw_vec::RawVecInner<A>::with_capacity_in
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.16
    u32wrapping_sub
    push.1114208
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.0
    push.256
    push.4
    dup.3
    u32wrapping_add
    movup.4
    swap.6
    movdn.4
    movup.3
    swap.5
    movdn.3
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::alloc::raw_vec::RawVecInner<A>::try_allocate_in
    trace.252
    nop
    push.8
    dup.1
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.4
    dup.2
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.0
    push.1
    movup.2
    neq
    neq
    if.true
        movup.3
        drop
        push.12
        dup.2
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_sw
        trace.252
        nop
        push.4
        dup.4
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::store_sw
        trace.252
        nop
        movup.2
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::store_sw
        trace.252
        nop
        push.16
        u32wrapping_add
        push.1114208
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::store_sw
        trace.252
        nop
    else
        movup.2
        drop
        push.12
        movup.2
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_sw
        trace.252
        nop
        swap.1
        trace.240
        nop
        exec.::miden:base/note-script@1.0.0::p2id::alloc::raw_vec::handle_error
        trace.252
        nop
        push.0
        assert
    end
end

proc.miden_base_sys::bindings::account::get_id
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.16
    u32wrapping_sub
    push.1114208
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.8
    dup.1
    u32wrapping_add
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::miden::account::get_id
    trace.252
    nop
    push.8
    dup.1
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_dw
    trace.252
    nop
    movup.3
    push.8
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_dw
    trace.252
    nop
    push.16
    u32wrapping_add
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.miden_base_sys::bindings::note::get_inputs
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.16
    u32wrapping_sub
    push.1114208
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.1114212
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.1048632
    u32wrapping_add
    push.4
    push.8
    dup.3
    u32wrapping_add
    dup.1
    swap.2
    swap.1
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::alloc::raw_vec::RawVecInner<A>::with_capacity_in
    trace.252
    nop
    push.8
    dup.1
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.12
    dup.2
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.2
    dup.1
    swap.1
    u32shr
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::miden::note::get_inputs
    trace.252
    nop
    push.8
    dup.5
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.4
    dup.4
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    movup.2
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.16
    u32wrapping_add
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.miden_base_sys::bindings::note::get_assets
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.16
    u32wrapping_sub
    push.1114208
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.1114212
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.1048648
    u32wrapping_add
    push.16
    push.8
    dup.3
    u32wrapping_add
    dup.1
    swap.2
    swap.1
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::alloc::raw_vec::RawVecInner<A>::with_capacity_in
    trace.252
    nop
    push.8
    dup.1
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.12
    dup.2
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.2
    dup.1
    swap.1
    u32shr
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::miden::note::get_assets
    trace.252
    nop
    push.8
    dup.5
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.4
    dup.4
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    movup.2
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.16
    u32wrapping_add
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.intrinsics::felt::eq
    eq
end

proc.alloc::raw_vec::RawVecInner<A>::deallocate
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.16
    u32wrapping_sub
    push.1114208
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.4
    dup.1
    u32wrapping_add
    swap.1
    swap.4
    swap.3
    swap.2
    swap.1
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::alloc::raw_vec::RawVecInner<A>::current_memory
    trace.252
    nop
    push.8
    dup.1
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.0
    push.0
    dup.2
    eq
    neq
    if.true
        drop
    else
        push.4
        dup.2
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_sw
        trace.252
        nop
        push.12
        dup.3
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_sw
        trace.252
        nop
        movdn.2
        trace.240
        nop
        exec.::miden:base/note-script@1.0.0::p2id::<alloc::alloc::Global as core::alloc::Allocator>::deallocate
        trace.252
        nop
    end
    push.16
    u32wrapping_add
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.alloc::raw_vec::RawVecInner<A>::try_allocate_in
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.16
    u32wrapping_sub
    push.1114208
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    dup.2
    push.0
    push.0
    dup.7
    u32wrapping_sub
    push.4294967295
    movup.9
    dup.9
    u32wrapping_add
    u32wrapping_add
    u32and
    push.0
    trace.240
    nop
    exec.::intrinsics::i64::wrapping_mul
    trace.252
    nop
    push.0
    push.32
    push.0
    dup.0
    push.2147483648
    u32and
    eq.2147483648
    assertz
    assertz
    dup.0
    push.4294967295
    u32lte
    assert
    dup.3
    dup.3
    movup.2
    trace.240
    nop
    exec.::std::math::u64::shr
    trace.252
    nop
    drop
    neq
    if.true
        drop
        drop
        movup.2
        drop
        movup.2
        drop
        movup.2
        drop
        push.0
        push.3735929054
        dup.0
        dup.1
        swap.4
        swap.1
        swap.3
        swap.5
    else
        drop
        push.0
        push.2147483648
        dup.7
        u32wrapping_sub
        dup.2
        swap.1
        u32lte
        neq
        dup.0
        if.true
            push.0
            dup.2
            neq
            if.true
                push.0
                movup.6
                neq
                if.true
                    push.1
                    dup.3
                    dup.7
                    dup.4
                    swap.2
                    trace.240
                    nop
                    exec.::miden:base/note-script@1.0.0::p2id::alloc::alloc::Global::alloc_impl
                    trace.252
                    nop
                    dup.2
                    push.4
                    dup.1
                    swap.1
                    u32mod
                    u32assert
                    assertz
                    u32divmod.4
                    swap.1
                    trace.240
                    nop
                    exec.::intrinsics::mem::load_sw
                    trace.252
                    nop
                else
                    push.8
                    dup.3
                    u32wrapping_add
                    dup.6
                    dup.3
                    swap.2
                    trace.240
                    nop
                    exec.::miden:base/note-script@1.0.0::p2id::<alloc::alloc::Global as core::alloc::Allocator>::allocate
                    trace.252
                    nop
                    push.8
                    dup.3
                    add
                    u32assert
                    push.4
                    dup.1
                    swap.1
                    u32mod
                    u32assert
                    assertz
                    u32divmod.4
                    swap.1
                    trace.240
                    nop
                    exec.::intrinsics::mem::load_sw
                    trace.252
                    nop
                end
                push.0
                push.0
                dup.2
                eq
                neq
                dup.0
                if.true
                    movup.6
                    movup.2
                    drop
                    drop
                    push.8
                    dup.5
                    add
                    u32assert
                    push.4
                    dup.1
                    swap.1
                    u32mod
                    u32assert
                    assertz
                    movup.3
                    swap.1
                    u32divmod.4
                    swap.1
                    trace.240
                    nop
                    exec.::intrinsics::mem::store_sw
                    trace.252
                    nop
                    push.4
                    dup.4
                    add
                    u32assert
                    push.4
                    dup.1
                    swap.1
                    u32mod
                    u32assert
                    assertz
                    movup.5
                    swap.1
                    u32divmod.4
                    swap.1
                    trace.240
                    nop
                    exec.::intrinsics::mem::store_sw
                    trace.252
                    nop
                else
                    movup.7
                    movup.4
                    drop
                    drop
                    push.8
                    dup.5
                    add
                    u32assert
                    push.4
                    dup.1
                    swap.1
                    u32mod
                    u32assert
                    assertz
                    movup.2
                    swap.1
                    u32divmod.4
                    swap.1
                    trace.240
                    nop
                    exec.::intrinsics::mem::store_sw
                    trace.252
                    nop
                    push.4
                    dup.4
                    add
                    u32assert
                    push.4
                    dup.1
                    swap.1
                    u32mod
                    u32assert
                    assertz
                    movup.5
                    swap.1
                    u32divmod.4
                    swap.1
                    trace.240
                    nop
                    exec.::intrinsics::mem::store_sw
                    trace.252
                    nop
                end
                push.0
                push.1
                movup.2
                cdrop
            else
                movup.2
                swap.5
                movdn.2
                swap.4
                swap.1
                drop
                drop
                drop
                push.8
                dup.1
                add
                u32assert
                push.4
                dup.1
                swap.1
                u32mod
                u32assert
                assertz
                movup.4
                swap.1
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::store_sw
                trace.252
                nop
                push.4
                dup.1
                add
                u32assert
                push.4
                dup.1
                swap.1
                u32mod
                u32assert
                assertz
                push.0
                swap.1
                u32divmod.4
                swap.1
                trace.240
                nop
                exec.::intrinsics::mem::store_sw
                trace.252
                nop
                push.0
                swap.1
                swap.3
                swap.2
                swap.1
            end
        else
            swap.1
            drop
            movup.3
            drop
            movup.3
            drop
            movup.3
            drop
            push.3735929054
        end
        push.0
        push.1
        dup.3
        cdrop
        push.3735929054
        dup.3
        dup.5
        swap.1
        cdrop
        push.3735929054
        dup.4
        dup.7
        swap.1
        cdrop
        push.3735929054
        dup.5
        movup.2
        swap.7
        movdn.2
        cdrop
        push.3735929054
        movup.2
        swap.7
        movdn.2
        swap.1
        swap.5
        cdrop
        swap.1
        swap.5
        swap.4
        swap.2
        swap.3
        swap.1
    end
    movup.5
    eq.0
    if.true
        movup.2
        drop
        movup.2
        drop
        movup.2
        drop
        push.4
        dup.1
        add
        u32assert
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        push.0
        swap.1
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::store_sw
        trace.252
        nop
        push.1
        swap.1
    else
        drop
        drop
    end
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.16
    u32wrapping_add
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.<alloc::alloc::Global as core::alloc::Allocator>::allocate
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.16
    u32wrapping_sub
    push.1114208
    dup.1
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.0
    push.8
    dup.2
    u32wrapping_add
    movup.2
    swap.5
    movdn.2
    swap.1
    swap.3
    swap.4
    swap.1
    trace.240
    nop
    exec.::miden:base/note-script@1.0.0::p2id::alloc::alloc::Global::alloc_impl
    trace.252
    nop
    push.12
    dup.2
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    push.8
    dup.3
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::load_sw
    trace.252
    nop
    dup.2
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.4
    movup.2
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    push.16
    u32wrapping_add
    push.1114208
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.alloc::alloc::Global::alloc_impl
    push.0
    push.0
    dup.4
    eq
    neq
    if.true
        movup.3
        drop
        swap.1
    else
        trace.240
        nop
        exec.::miden:base/note-script@1.0.0::p2id::__rustc::__rust_no_alloc_shim_is_unstable_v2
        trace.252
        nop
        push.0
        movup.4
        neq
        if.true
            swap.1
            dup.2
            trace.240
            nop
            exec.::miden:base/note-script@1.0.0::p2id::__rustc::__rust_alloc_zeroed
            trace.252
            nop
        else
            swap.1
            dup.2
            trace.240
            nop
            exec.::miden:base/note-script@1.0.0::p2id::__rustc::__rust_alloc
            trace.252
            nop
        end
    end
    push.4
    dup.2
    add
    u32assert
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    movup.3
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
    swap.1
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.alloc::raw_vec::RawVecInner<A>::current_memory
    push.0
    push.0
    dup.5
    eq
    neq
    if.true
        movdn.3
        drop
        drop
        drop
        push.0
        push.4
    else
        dup.1
        push.4
        dup.1
        swap.1
        u32mod
        u32assert
        assertz
        u32divmod.4
        swap.1
        trace.240
        nop
        exec.::intrinsics::mem::load_sw
        trace.252
        nop
        push.0
        push.0
        dup.2
        eq
        neq
        dup.0
        if.true
            swap.1
            drop
            movup.2
            drop
            movup.2
            drop
            movup.2
            drop
            push.0
        else
            push.4
            dup.3
            add
            u32assert
            push.4
            dup.1
            swap.1
            u32mod
            u32assert
            assertz
            movup.5
            swap.1
            u32divmod.4
            swap.1
            trace.240
            nop
            exec.::intrinsics::mem::store_sw
            trace.252
            nop
            push.4
            movup.4
            add
            u32assert
            push.4
            dup.1
            swap.1
            u32mod
            u32assert
            assertz
            u32divmod.4
            swap.1
            trace.240
            nop
            exec.::intrinsics::mem::load_sw
            trace.252
            nop
            dup.3
            push.4
            dup.1
            swap.1
            u32mod
            u32assert
            assertz
            u32divmod.4
            swap.1
            trace.240
            nop
            exec.::intrinsics::mem::store_sw
            trace.252
            nop
            swap.3
            trace.240
            nop
            exec.::intrinsics::i32::wrapping_mul
            trace.252
            nop
            movup.2
            swap.1
        end
        push.8
        push.4
        movup.3
        cdrop
    end
    movup.2
    u32wrapping_add
    push.4
    dup.1
    swap.1
    u32mod
    u32assert
    assertz
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_sw
    trace.252
    nop
end

proc.<alloc::alloc::Global as core::alloc::Allocator>::deallocate
    push.0
    push.0
    dup.4
    eq
    neq
    if.true
        drop
        drop
        drop
    else
        movup.2
        swap.1
        trace.240
        nop
        exec.::miden:base/note-script@1.0.0::p2id::__rustc::__rust_dealloc
        trace.252
        nop
    end
end

proc.alloc::raw_vec::handle_error
    drop
    drop
    drop
    push.0
    assert
end

proc.core::ptr::alignment::Alignment::max
    push.0
    dup.2
    dup.2
    swap.1
    u32gt
    neq
    cdrop
end

proc.miden::account::get_id
    trace.240
    nop
    exec.::miden::account::get_id
    trace.252
    nop
    movup.2
    dup.0
    movup.2
    swap.1
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
    push.4
    add
    u32assert
    u32divmod.4
    swap.1
    trace.240
    nop
    exec.::intrinsics::mem::store_felt
    trace.252
    nop
end

proc.miden::note::get_inputs
    trace.240
    nop
    exec.::miden::note::get_inputs
    trace.252
    nop
    swap.1
    drop
end

proc.miden::note::get_assets
    trace.240
    nop
    exec.::miden::note::get_assets
    trace.252
    nop
    swap.1
    drop
end
`;
