/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_outputs_free(a: number, b: number): void;
export function __wbg_get_outputs_account_delta_storage(a: number): Array;
export function __wbg_set_outputs_account_delta_storage(a: number, b: number, c: number): void;
export function __wbg_get_outputs_account_delta_vault(a: number): Array;
export function __wbg_set_outputs_account_delta_vault(a: number, b: number, c: number): void;
export function __wbg_get_outputs_account_delta_nonce(a: number): number;
export function __wbg_set_outputs_account_delta_nonce(a: number, b: number): void;
export function __wbg_get_outputs_account_code_commitment(a: number): Array;
export function __wbg_set_outputs_account_code_commitment(a: number, b: number, c: number): void;
export function __wbg_get_outputs_account_storage_commitment(a: number): Array;
export function __wbg_set_outputs_account_storage_commitment(a: number, b: number, c: number): void;
export function __wbg_get_outputs_account_vault_commitment(a: number): Array;
export function __wbg_set_outputs_account_vault_commitment(a: number, b: number, c: number): void;
export function __wbg_get_outputs_account_hash(a: number): Array;
export function __wbg_set_outputs_account_hash(a: number, b: number, c: number): void;
export function __wbg_get_outputs_cycle_count(a: number): number;
export function __wbg_set_outputs_cycle_count(a: number, b: number): void;
export function __wbg_get_outputs_trace_length(a: number): number;
export function __wbg_set_outputs_trace_length(a: number, b: number): void;
export function execute(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): Array;
export function __wbg_clientaccount_free(a: number, b: number): void;
export function __wbg_get_clientaccount_id_hex(a: number): Array;
export function __wbg_set_clientaccount_id_hex(a: number, b: number, c: number): void;
export function generate_secret_key(): Array;
export function clientaccount_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number): Array;
export function clientaccount_create_note(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): Array;
export function clientaccount_consume_note(a: number, b: number, c: number, d: number): Array;
export function clientaccount_assets(a: number): Array;
export function __wbg_clientnote_free(a: number, b: number): void;
export function clientnote_id(a: number): Array;
export function __wbg_clientasset_free(a: number, b: number): void;
export function clientasset_faucet_id(a: number): Array;
export function clientasset_amount(a: number): number;
export const __wbindgen_export_0: WebAssembly.Table;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __externref_table_dealloc(a: number): void;
export function __externref_drop_slice(a: number, b: number): void;
export function __wbindgen_start(): void;
